//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIBFormDesigner.Designer.Form {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormulaEditorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormulaEditorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIBFormDesigner.Designer.Form.FormulaEditorResource", typeof(FormulaEditorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkValueWithOperator(userPattern, &quot;UserPatternName&quot;, &quot;EQUAL&quot;);.
        /// </summary>
        internal static string checkValueWithOperatorMethod {
            get {
                return ResourceManager.GetString("checkValueWithOperatorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clearFormData(&quot;FormPatternName&quot;);.
        /// </summary>
        internal static string clearFormDataMethodMethod {
            get {
                return ResourceManager.GetString("clearFormDataMethodMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session.getAttribute(&quot;rowId&quot;);.
        /// </summary>
        internal static string getAttributeMethod {
            get {
                return ResourceManager.GetString("getAttributeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getSessionData(&quot;userPatterns&quot;);.
        /// </summary>
        internal static string getSessionDataMethod {
            get {
                return ResourceManager.GetString("getSessionDataMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invokeComponent(&quot;dbComponent&quot;,&quot;executeList&quot;,&quot;com.oxymedical.component.db.DBComponent&quot;,&quot;query&quot;);.
        /// </summary>
        internal static string invokeComponentExecuteDBMethod {
            get {
                return ResourceManager.GetString("invokeComponentExecuteDBMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invokeComponent(&quot;dbComponent&quot;,&quot;executeQuery&quot;,&quot;com.oxymedical.component.db.DBComponent&quot;,&quot;query&quot;);.
        /// </summary>
        internal static string invokeComponentExecuteQueryMethod {
            get {
                return ResourceManager.GetString("invokeComponentExecuteQueryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invokeComponent(&quot;dbComponent&quot;,&quot;save&quot;,&quot;com.oxymedical.component.db.DBComponent&quot;,&quot;formPatternName&quot;);.
        /// </summary>
        internal static string invokeComponentSaveMethod {
            get {
                return ResourceManager.GetString("invokeComponentSaveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invokeComponent(&quot;com.oxymedical.component.useradmin&quot;,&quot;authenticateUserEx&quot;,&quot;com.oxymedical.component.useradmin.UserAdminComponent&quot;,&quot;[Login TextBox Id]&quot;);.
        /// </summary>
        internal static string invokeComponentUALoginAuthenticationMethod {
            get {
                return ResourceManager.GetString("invokeComponentUALoginAuthenticationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invokeComponent(&quot;dbComponent&quot;,&quot;updateRecord&quot;,&quot;com.oxymedical.component.db.DBComponent&quot;,&quot;query&quot;);.
        /// </summary>
        internal static string invokeComponentUpdateDBMethod {
            get {
                return ResourceManager.GetString("invokeComponentUpdateDBMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invokeComponent(&quot;com.oxymedical.component.HL7Component&quot;,&quot;sendandrecieve&quot;,&quot;com.oxymedical.component.HL7Component.HL7Component&quot;,&quot;FormPatternName&quot;);.
        /// </summary>
        internal static string invokeHL7ComponentMethod {
            get {
                return ResourceManager.GetString("invokeHL7ComponentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invokeComponent(&quot;id.rendering&quot;,&quot;moveForm&quot;,&quot;com.oxymedical.component.renderer.RendererComponent&quot;,&quot;FormPatternName&quot;);.
        /// </summary>
        internal static string moveMethod {
            get {
                return ResourceManager.GetString("moveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setDataStatus(&quot;Status&quot;, &quot;NextForm&quot;, &quot;DatapatternName&quot;);.
        /// </summary>
        internal static string setDataStatusMethod {
            get {
                return ResourceManager.GetString("setDataStatusMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updateSession(&quot;rowId&quot;, null);.
        /// </summary>
        internal static string updateSessionMethod {
            get {
                return ResourceManager.GetString("updateSessionMethod", resourceCulture);
            }
        }
    }
}
