//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIBFormDesigner.Designer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIBFormDesigner.Designer.Common.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop database if exists auditlogging ;
        ///
        ///create database auditlogging ;
        ///
        ///use auditlogging ;
        ///
        ///create table ContainerType (containerTypeId varchar(100), containerTypeName varchar (50),
        ///CONSTRAINT containerTypeIdCT_PK primary key ( containerTypeId));
        ///
        ///create table Container ( containerId  varchar(100) , containerTypeId  varchar(100) ,
        ///CONSTRAINT containerIdCO_PK primary key ( containerId), 
        ///CONSTRAINT containerTypeIdCO_FK FOREIGN KEY (containerTypeId) REFERENCES ContainerType (containerTypeId));
        ///
        ///c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auditlogging {
            get {
                return ResourceManager.GetString("auditlogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop database if exists billingtracking;
        ///create database billingtracking;
        ///use billingtracking;
        ///
        ///create table Transaction ( transactionId  varchar(100) , transactionType  varchar(50)  , transactionDesc  varchar(50),
        ///CONSTRAINT transactionId_PK primary key ( transactionId) );
        ///
        ///create table Currency ( currencyId varchar(100), currency varchar(50),
        ///CONSTRAINT currencyIdCU_PK primary key ( currencyId));
        ///
        ///create table BillingCycle ( billingCycleId varchar(100), billingCycleDesc varchar(50),
        ///CONSTRAINT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string billingtracking {
            get {
                return ResourceManager.GetString("billingtracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop database if exists useradmin;
        ///create database useradmin;
        ///use useradmin;
        ///create table Account_ 
        ///(
        ///	accountId varchar(100) not null primary key,
        ///	companyId varchar(100) not null,
        ///	userId varchar(100) not null,
        ///	userName varchar(100) null,
        ///	createDate datetime null,
        ///	modifiedDate datetime null,
        ///	parentAccountId varchar(100) null,
        ///	name varchar(100) null
        ///);
        ///
        ///create table Address 
        ///(
        ///	addressId varchar(100) not null primary key,
        ///	companyId varchar(100) not null,
        ///	userId varchar(100) not nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSQL {
            get {
                return ResourceManager.GetString("CreateSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop database if exists maintenance ;
        ///create database maintenance ;
        ///use maintenance ;
        ///create table ComponentMasterInfo ( componentId  Char( 25)  PRIMARY KEY   , indexId  INT  ,  INDEX ( componentId) ) TYPE = INNODB ;
        ///create table ComponentDefectInfo ( defectId  Char( 25)  PRIMARY KEY   , defectCompId  Char( 25)   , occurence_counter   INT  , severity  INT  , defect_occured  TIMESTAMP  ,  INDEX ( defectId) ) TYPE = INNODB ;
        ///create table ComponentActionInfo ( actionId  Char( 25)   , maintenance_Id  Char( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maintenance {
            get {
                return ResourceManager.GetString("maintenance", resourceCulture);
            }
        }
    }
}
